const USER_TYPES = {
  ADMIN: "ADMIN",
  COMPANY: "COMPANY",
  EMPLOYEE: "EMPLOYEE"
};

const BACKUP_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  SUBMITTED: "SUBMITTED"
};

module.exports = {
  USER_TYPES,
  BACKUP_STATUS
};
