const USER_TYPES = {
  ADMIN: "ADMIN",
  COMPANY: "COMPANY",
  EMPLOYEE: "EMPLOYEE"
};

const BACKUP_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  SUBMITTED: "SUBMITTED"
};

const COMPANY_STAGES = {
  ONBOARDING: "ONBOARDING",
  ACTIVE: "ACTIVE",
  PAYMENT_PENDING: "PAYMENT_PENDING",
  SUSPENDED: "SUSPENDED"
};

module.exports = {
  USER_TYPES,
  BACKUP_STATUS,
  COMPANY_STAGES
};
